site_logo: /assets/uploads/logo.svg
site_logo_dark: /assets/uploads/logo-dark.svg
contact_details:
  tel: +44 (0)1223 334088
  fax: +44 (0)1223 334089
  email: contact@mlatcl.cam.ac.uk
  address: |-
    15 JJ Thomson Ave,  \
    Cambridge,  \
    CB3 0FD
social_details:
  twitter_link: https://twitter.com/
  facebook_link: https://facebook.com/
  instagram_link: https://instagram.com/
footer_images:
  - image: /assets/uploads/logo.svg
    link: "#"
  - image: /assets/uploads/cambridge-university.png
    link: https://www.cam.ac.uk/
