backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

media_folder: 'assets/uploads'

collections:

  # General Website Settings
  - name: 'website-settings'
    label: 'Website Settings'
    files:
      # Website Settings
      - label: 'Website Settings'
        name: 'site'
        file: '_data/site.yml'
        editor:
          preview: false
        fields:
          # Site Logo
          - label: 'Site Logo'
            name: 'site_logo'
            widget: 'image'
          - label: 'Site Logo Dark'
            name: 'site_logo_dark'
            widget: 'image'
          # Contact Details
          - label: 'Contact Details'
            name: 'contact_details'
            collapsed: true
            widget: 'object'
            fields:
              - label: 'Address'
                name: 'address'
                widget: 'markdown'
              - label: 'Tel'
                name: 'tel'
                widget: 'string'
              - label: 'Fax'
                name: 'fax'
                widget: 'string'
              - label: 'Email'
                name: 'email'
                widget: 'string'
          # Social Details
          - label: 'Social Details'
            name: 'social_details'
            collapsed: true
            widget: 'object'
            fields:
              - label: 'Twitter'
                name: 'twitter_link'
                widget: 'string'
              - label: 'Facebook'
                name: 'facebook_link'
                widget: 'string'
              - label: 'Instagram'
                name: 'instagram_link'
                widget: 'string'
          # Footer Settings
          - label: 'Footer Images'
            name: 'footer_images'
            collapsed: true
            widget: 'list'
            required: false
            fields: 
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Link'
                name: 'link'
                widget: 'string'
      # Navigation Menus
      - label: 'Navigation Menus'
        name: 'navigation_menus'
        file: '_data/nav.yml'
        editor:
          preview: false
        fields:
          # Main Nav
          - label: 'Main Nav'
            name: 'main_nav'
            collapsed: true
            minimize_collapsed: true
            widget: 'list'
            required: false
            fields: 
              - label: 'Label'
                name: 'label'
                widget: 'string'
              - label: 'Link'
                name: 'link'
                widget: 'string'
              - label: 'Submenu Item'
                name: 'submenu_item'
                collapsed: true
                minimize_collapsed: true
                widget: 'list'
                required: false
                fields: 
                  - label: 'Label'
                    name: 'label'
                    widget: 'string'
                  - label: 'Link'
                    name: 'link'
                    widget: 'string'
          # Footer Nav
          - label: 'Footer Nav'
            name: 'footer_nav'
            collapsed: true
            minimize_collapsed: true
            widget: 'list'
            required: false
            fields: 
              - label: 'Label'
                name: 'label'
                widget: 'string'
              - label: 'Link'
                name: 'link'
                widget: 'string'
              - label: 'Submenu Item'
                name: 'submenu_item'
                collapsed: true
                minimize_collapsed: true
                widget: 'list'
                required: false
                fields: 
                  - label: 'Label'
                    name: 'label'
                    widget: 'string'
                  - label: 'Link'
                    name: 'link'
                    widget: 'string'
          # Top Nav
          - label: 'Top Bar'
            name: 'top_bar'
            collapsed: true
            widget: 'object'
            fields:
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Link'
                name: 'link'
                widget: 'string'
              - label: 'Top Bar Nav'
                name: 'top_bar_nav'
                collapsed: true
                minimize_collapsed: true
                widget: 'list'
                required: false
                fields: 
                  - label: 'Label'
                    name: 'label'
                    widget: 'string'
                  - label: 'Link'
                    name: 'link'
                    widget: 'string'

  # Pages
  - name: 'pages'
    label: 'Pages'
    files:
      # Homepage
      - label: 'Homepage'
        name: 'homepage'
        file: '_data/homepage.yml'
        editor:
          preview: false
        fields:
          # Hero Section
          - label: 'Hero'
            name: 'hero'
            collapsed: true
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
          # About Section
          - label: 'About'
            name: 'about'
            collapsed: true
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Heading'
                name: 'heading'
                widget: 'string'
              - label: 'Content'
                name: 'content'
                widget: 'text'
              - label: 'Link Label'
                name: 'link_label'
                widget: 'string'
              - label: 'Link URL'
                name: 'link_url'
                widget: 'string'
              - label: 'Image'
                name: 'image'
                widget: 'image'
          # Research Section
          - label: 'Research'
            name: 'research'
            collapsed: true
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Heading'
                name: 'heading'
                widget: 'string'
              - label: 'Content'
                name: 'content'
                widget: 'text'
              - label: 'Link Label'
                name: 'link_label'
                widget: 'string'
              - label: 'Link URL'
                name: 'link_url'
                widget: 'string'
              - label: 'Image'
                name: 'image'
                widget: 'image'
          # Partners
          - label: 'Partners'
            name: 'partners'
            collapsed: true
            minimize_collapsed: true
            widget: 'list'
            fields: 
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Link'
                name: 'link'
                widget: 'string'
      # About
      - label: 'About'
        name: 'about'
        file: '_data/about.yml'
        editor:
          preview: false
        fields:
          # Hero Section
          - label: 'Hero'
            name: 'hero'
            collapsed: true
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
          # Content
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
          # Partners
          - label: 'Partners'
            name: 'partners'
            collapsed: true
            minimize_collapsed: true
            widget: 'list'
            fields: 
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Link'
                name: 'link'
                widget: 'string'
          # Grid
          - label: 'Grid'
            name: 'grid'
            collapsed: true
            minimize_collapsed: true
            widget: 'list'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Description'
                name: 'description'
                widget: 'string'
              - label: 'Link'
                name: 'link'
                widget: 'string'
              - label: 'Image'
                name: 'image'
                widget: 'image'
      # Contact
      - label: 'Contact'
        name: 'contact'
        file: '_data/contact.yml'
        editor:
          preview: false
        fields:
          # Hero Section
          - label: 'Hero'
            name: 'hero'
            collapsed: true
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
          # Contact Details
          - label: 'Contact Details'
            name: 'contact_details'
            collapsed: true
            widget: 'object'
            fields:
              - label: 'Image'
                name: 'image'
                widget: 'image'
      # Resources
      - label: 'Resources'
        name: 'resources'
        file: '_data/resources.yml'
        editor:
          preview: false
        fields:
          # Hero Section
          - label: 'Hero'
            name: 'hero'
            collapsed: true
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
          # Resources Section
          - label: 'Resources'
            name: 'resources'
            collapsed: true
            minimize_collapsed: true
            widget: 'list'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Category'
                name: 'category'
                widget: 'select'
                options: ["Policy", "Teaching", "Software"]
              - label: 'Link'
                name: 'link'
                widget: 'string'
              - label: 'Icon'
                name: 'icon'
                widget: 'image'


  # Blog Collection
  - label: 'Blog'
    name: 'Blog'
    folder: '_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'blog-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'text'
      - label: 'Featured Image'
        name: 'featured_image'
        widget: 'image'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  # News Collection
  - label: 'News'
    name: 'News'
    folder: '_news'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'news-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'text'
      - label: "Category"
        name: "category"
        widget: "select"
        multiple: true
        options:
          - { label: "AI Deployment and System Design", value: "ai-deployment-and-system-design" }
          - { label: "AI for Research and Innovation", value: "ai-for-research-and-innovation" }
          - { label: "AI Policy and Data Governance", value: "ai-policy-and-data-governance" }
          - { label: "Machine Learning Theory and Methods", value: "machine-learning-theory-and-methods" }
      - label: 'Featured Image'
        name: 'featured_image'
        widget: 'image'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  # Events Collection
  - label: 'Events'
    name: 'events'
    folder: '_events'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'event-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Event Date'
        name: 'event_date'
        widget: 'date'
        date_format: "DD.MM.YYYY"
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'text'
      - label: 'Featured Image'
        name: 'featured_image'
        widget: 'image'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
  
  # People Collection
  - label: 'People'
    name: 'people'
    folder: '_people/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'people-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'text'
      - label: 'Featured Image'
        name: 'featured_image'
        widget: 'image'
      - label: 'LinkedIn'
        name: 'linkedin'
        widget: 'string'
        required: false
      - label: 'Twitter'
        name: 'twitter'
        widget: 'string'
        required: false
      - label: 'Facebook'
        name: 'facebook'
        widget: 'string'
        required: false
      - label: 'Email'
        name: 'email'
        widget: 'string'
        required: false
      - label: 'Biography'
        name: 'biography'
        widget: 'markdown'
        required: false
      - label: 'Related Publications'
        name: 'publications'
        widget: 'relation'
        collection: 'Publications'
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        multiple: true
        required: false

  # Research Collection
  - label: 'Research'
    name: 'research'
    folder: '_research/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'research-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'text'
      - label: 'Featured Image'
        name: 'featured_image'
        widget: 'image'
      - label: 'Overview Short'
        name: 'overview_short'
        widget: 'markdown'
      - label: 'Overview Long'
        name: 'overview_long'
        widget: 'markdown'
        required: false
      - label: 'Related Projects'
        name: 'projects'
        widget: 'relation'
        collection: 'projects'
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        multiple: true
        required: false
      - label: 'Related People'
        name: 'people'
        widget: 'relation'
        collection: 'people'
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        multiple: true
        required: false

  # Project Collection
  - label: 'Projects'
    name: 'projects'
    folder: '_projects/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'project-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'text'
      - label: 'Featured Image'
        name: 'featured_image'
        widget: 'image'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
      - label: 'Project Funders'
        name: 'project_funders'
        collapsed: true
        minimize_collapsed: true
        required: false
        widget: 'list'
        fields: 
          - label: 'Image'
            name: 'image'
            widget: 'image'
          - label: 'Link'
            name: 'link'
            widget: 'string'
      - label: 'Related People'
        name: 'people'
        widget: 'relation'
        collection: 'people'
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        multiple: true
        required: false
      - label: 'Related Publications'
        name: 'publications'
        widget: 'relation'
        collection: 'Publications'
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        multiple: true
        required: false

  # Publications Collection
  - label: 'Publications'
    name: 'Publications'
    folder: '_publications'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'publication-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Author'
        name: 'author'
        widget: 'string'
      - label: 'References'
        name: 'references'
        widget: 'string'
      - label: 'Featured Image'
        name: 'featured_image'
        widget: 'image'
        required: false
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
  
  # Opportunities Collection
  - label: 'Opportunities'
    name: 'opportunities'
    folder: '_opportunities/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'opportunities-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'text'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'    