backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

media_folder: 'assets/uploads'

collections:

  # General Website Settings
  - name: 'website-settings'
    label: 'Website Settings'
    files:
      - label: 'Website Settings'
        name: 'site'
        file: '_data/site.yml'
        fields:
          - label: 'Tel'
            name: 'tel'
            widget: 'string'
          - label: 'Fax'
            name: 'fax'
            widget: 'string'
          - label: 'Email'
            name: 'email'
            widget: 'string'

  # Pages
  - name: 'pages'
    label: 'Pages'
    files:
      # Homepage
      - label: 'Homepage'
        name: 'homepage'
        file: '_data/homepage.yml'
        fields:
          # About Section
          - label: 'About'
            name: 'about'
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Heading'
                name: 'heading'
                widget: 'string'
              - label: 'Content'
                name: 'content'
                widget: 'text'
              - label: 'Image'
                name: 'image'
                widget: 'image'
          # Research Section
          - label: 'Research'
            name: 'research'
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Heading'
                name: 'heading'
                widget: 'string'
              - label: 'Content'
                name: 'content'
                widget: 'text'
              - label: 'Image'
                name: 'image'
                widget: 'image'
          # Logo Grid
          - label: 'Logo Grid'
            name: 'logo-grid'
            widget: 'list'
            fields: 
              - label: 'Image'
                name: 'image'
                widget: 'image'

  # Blog Collection
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    fields:
      - name: 'Title'

  # People Collection
  - name: 'people'
    label: 'People'
    folder: '_people/'
    create: true
    fields:
      - name: 'Title'

  # Research Collection
  - name: 'research'
    label: 'Research'
    folder: '_research/'
    create: true
    fields:
      - name: 'Title'