backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

media_folder: 'assets/uploads'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    fields:
      - { name: Title }
  - name: 'people'
    label: 'People'
    folder: '_people/'
    create: true
    fields:
      - { name: Title }
  - name: 'researcg'
    label: 'Research'
    folder: '_research/'
    create: true
    fields:
      - { name: Title }