backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

media_folder: 'assets/uploads'

collections:
  - name: 'website-settings'
    label: 'Website Settings'
    files:
      - label: 'Website Settings'
        name: 'site'
        file: '_data/site.yml'
        fields:
          - {
            label: 'Tel',
            name: 'tel',
            widget: 'string',
          }
          - {
            label: 'Fax',
            name: 'fax',
            widget: 'string',
          }
          - {
            label: 'Email',
            name: 'email',
            widget: 'string',
          }
  
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Homepage'
        name: 'homepage'
        file: '_data/homepage.yml'
        fields:
          - {
            label: 'About',
            name: 'about',
            widget: 'object',
          }

  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    fields:
      - { 
          name: Title,
        }

  - name: 'people'
    label: 'People'
    folder: '_people/'
    create: true
    fields:
      - { 
          name: Title,
        }

  - name: 'research'
    label: 'Research'
    folder: '_research/'
    create: true
    fields:
      - { 
          name: Title,
        }