backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

media_folder: 'assets/uploads'

collections:

  # General Website Settings
  - name: 'website-settings'
    label: 'Website Settings'
    files:
      - label: 'Website Settings'
        name: 'site'
        file: '_data/site.yml'
        fields:
          - label: 'Tel'
            name: 'tel'
            widget: 'string'
          - label: 'Fax'
            name: 'fax'
            widget: 'string'
          - label: 'Email'
            name: 'email'
            widget: 'string'

  # Pages
  - name: 'pages'
    label: 'Pages'
    files:
      # Homepage
      - label: 'Homepage'
        name: 'homepage'
        file: '_data/homepage.yml'
        fields:
          # Hero Section
          - label: 'Hero'
            name: 'hero'
            collapsed: true
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
          # About Section
          - label: 'About'
            name: 'about'
            collapsed: true
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Heading'
                name: 'heading'
                widget: 'string'
              - label: 'Content'
                name: 'content'
                widget: 'text'
              - label: 'Image'
                name: 'image'
                widget: 'image'
          # Research Section
          - label: 'Research'
            name: 'research'
            collapsed: true
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Heading'
                name: 'heading'
                widget: 'string'
              - label: 'Content'
                name: 'content'
                widget: 'text'
              - label: 'Image'
                name: 'image'
                widget: 'image'
          # Partners
          - label: 'Partners'
            name: 'partners'
            collapsed: true
            minimize_collapsed: true
            widget: 'list'
            fields: 
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Link'
                name: 'link'
                widget: 'string'

  # Blog Collection
  - label: 'Blog'
    name: 'blog'
    folder: '_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'post-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'text'
      - label: 'Category'
        name: 'category'
        widget: 'select'
        options:
          - label: 'Event'
            value: 'event'
          - label: 'News'
            value: 'news'
      - label: 'Featured Image'
        name: 'featured-image'
        widget: 'image'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  # People Collection
  - label: 'People'
    name: 'people'
    folder: '_people/'
    create: true
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'people-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'text'
      - label: 'Featured Image'
        name: 'featured-image'
        widget: 'image'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  # Research Collection
  - label: 'Research'
    name: 'research'
    folder: '_research/'
    create: true
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'research-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'text'
      - label: 'Featured Image'
        name: 'featured-image'
        widget: 'image'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  # Project Collection
  - label: 'Projects'
    name: 'projects'
    folder: '_projects/'
    create: true
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'project-single'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'text'
      - label: 'Featured Image'
        name: 'featured-image'
        widget: 'image'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'